####
GET http://localhost:4004/odata/v4/employee
 
####
 
GET http://localhost:4004/odata/v4/employee/$metadata
 
####
 
GET http://localhost:4004/odata/v4/employee/employee
 
####
 
GET http://localhost:4004/odata/v4/employee/employee?$filter=startswith(nameFirst,'S')
 
####
 
GET http://localhost:4004/odata/v4/employee/employee?$orderby=salaryAmount desc&$top=2
 
 
 
####
POST http://localhost:4004/odata/v4/employee/employee
Content-Type: application/json
 
{
      "ID": "02BD2137-0890-1EKA-A6C2-BB55C19789FB",
      "nameFirst": "Sally",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "F",
      "Language": "E",
      "phoneNumber": "+1 224 374 524",
      "Email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "USD",
      "salaryAmount": 5555,
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch"
    }
 
####
POST http://localhost:4004/odata/v4/employee/employee
Content-Type: application/json
 
{
      "ID": "02BD2137-0890-1EKA-A6C2-BB55C19789FB",
      "nameFirst": "Sally",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "F",
      "Language": "E",
      "phoneNumber": "+1 224 374 524",
      "Email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "USD",
      "salaryAmount": 555533,
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch"
    }
 
####
POST http://localhost:4004/odata/v4/employee/employee
Content-Type: application/json
 
{
      "ID": "02BD2137-0890-1EKA-A6C2-BB55C14789FB",
      "nameFirst": "Sally",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "F",
      "Language": "E",
      "phoneNumber": "+1 224 374 524",
      "Email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "EUR",
      "salaryAmount": 533,
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch"
    }
 
####
PUT http://localhost:4004/odata/v4/employee/employee
Content-Type: application/json
 
{
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C19787FB",
      "nameFirst": "Sally",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "F",
      "Language": "E",
      "phoneNumber": "+1 224 374 524",
      "Email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "USD",
      "salaryAmount": 555433,
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch"
    }
 
 
####
PUT http://localhost:4004/odata/v4/employee/employee
Content-Type: application/json
 
{
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C19787FB",
      "nameFirst": "Saly",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "F",
      "Language": "E",
      "phoneNumber": "+1 224 374 524",
      "Email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "USD",
      "salaryAmount": 555433,
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch"
    }
####
 
DELETE http://localhost:4004/odata/v4/employee-set/employee/02BD2137-0890-1EEA-A6C2-BB55C19787FB
 
 
####
 
DELETE http://localhost:4004/odata/v4/employee-set/employee/02BD2137-0890-1EEA-A6C2-BB55C19A87FB
 
 